{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--56237a15-4fbb-4464-a4df-5e53ef4bfa3f",
    "created": "2024-08-13T16:10:55.605666Z",
    "modified": "2024-08-13T16:10:55.605671Z",
    "name": "No Title Available",
    "description": "python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2015-5159"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882"
        }
    ]
}