{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--a7c59405-4791-48fe-932b-138a9fffb6fc",
    "created": "2024-08-13T16:15:25.014311Z",
    "modified": "2024-08-13T16:15:25.014315Z",
    "name": "No Title Available",
    "description": "In GraphicsMagick 1.4 snapshot-20190403 Q8, there is a use-after-free in ThrowException and ThrowLoggedException of magick/error.c.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2019-19950"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://sourceforge.net/p/graphicsmagick/bugs/603/"
        },
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "http://hg.graphicsmagick.org/hg/GraphicsMagick/rev/44ab7f6c20b4"
        },
        {
            "name": "openSUSE-SU-2020:0055",
            "tags": [
                "vendor-advisory",
                "x_refsource_SUSE"
            ],
            "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00026.html"
        },
        {
            "name": "openSUSE-SU-2020:0145",
            "tags": [
                "vendor-advisory",
                "x_refsource_SUSE"
            ],
            "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00064.html"
        },
        {
            "name": "[debian-lts-announce] 20200129 [SECURITY] [DLA 2084-1] graphicsmagick security update",
            "tags": [
                "mailing-list",
                "x_refsource_MLIST"
            ],
            "url": "https://lists.debian.org/debian-lts-announce/2020/01/msg00029.html"
        },
        {
            "name": "DSA-4640",
            "tags": [
                "vendor-advisory",
                "x_refsource_DEBIAN"
            ],
            "url": "https://www.debian.org/security/2020/dsa-4640"
        }
    ]
}