{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--dcb3e5f0-6bdc-4a06-a9ca-35f9c39a569e",
    "created": "2024-08-13T16:07:37.608537Z",
    "modified": "2024-08-13T16:07:37.608542Z",
    "name": "No Title Available",
    "description": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2018-11499"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://github.com/sass/libsass/issues/2643"
        },
        {
            "name": "openSUSE-SU-2019:1791",
            "tags": [
                "vendor-advisory",
                "x_refsource_SUSE"
            ],
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00047.html"
        },
        {
            "name": "openSUSE-SU-2019:1800",
            "tags": [
                "vendor-advisory",
                "x_refsource_SUSE"
            ],
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00051.html"
        },
        {
            "name": "openSUSE-SU-2019:1883",
            "tags": [
                "vendor-advisory",
                "x_refsource_SUSE"
            ],
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00027.html"
        }
    ]
}