{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--86bdc44e-86fd-4b0e-9453-97505ec7c7f9",
    "created": "2024-08-13T16:14:24.476814Z",
    "modified": "2024-08-13T16:14:24.476818Z",
    "name": "No Title Available",
    "description": "traverser.py in Plone 2.1 through 4.1, 4.2.x through 4.2.5, and 4.3.x through 4.3.1 allows remote attackers with administrator privileges to cause a denial of service (infinite loop and resource consumption) via unspecified vectors related to \"retrieving information for certain resources.\"",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2013-4188"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://plone.org/products/plone/security/advisories/20130618-announcement"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://plone.org/products/plone-hotfix/releases/20130618"
        },
        {
            "name": "[oss-security] 20130801 Re: CVE Request -- Plone: 20130618 Hotfix (multiple vectors)",
            "tags": [
                "mailing-list",
                "x_refsource_MLIST"
            ],
            "url": "http://seclists.org/oss-sec/2013/q3/261"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=978449"
        }
    ]
}